name: Download translations
description: Download translations from Crowdin

inputs:
  crowdin-branch:
    description: 'Crowdin branch name'
    required: false
    default: 'v4'

runs:
  using: composite
  steps:
    - id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v4
      id: cache-crowdin
      with:
        key: crowdin-${{ inputs.crowdin-branch }}-${{ steps.get-date.outputs.date }}
        path: |-
          packages/api-generator/src/locale/**/*.json
          !packages/api-generator/src/locale/en/**/*.json
          packages/docs/src/pages/**/*.md
          !packages/docs/src/pages/en/**/*.md
          packages/docs/src/i18n/messages/*.json
          !packages/docs/src/i18n/messages/en.json
    - name: Download eo-UY
      if: ${{ steps.cache-crowdin.outputs.cache-hit != 'true' }}
      uses: crowdin/github-action@v2.7.1
      with:
        download_language: eo
        config: crowdin.yml
        upload_sources: false
        download_translations: true
        push_translations: false
        export_only_approved: false
        crowdin_branch_name: ${{ inputs.crowdin-branch }}
    - name: Download es-MX
      if: ${{ steps.cache-crowdin.outputs.cache-hit != 'true' }}
      uses: crowdin/github-action@v2.7.1
      with:
        download_language: es-MX
        config: crowdin.yml
        upload_sources: false
        download_translations: true
        push_translations: false
        export_only_approved: false
        crowdin_branch_name: ${{ inputs.crowdin-branch }}
    - name: Download ja-JP
      if: ${{ steps.cache-crowdin.outputs.cache-hit != 'true' }}
      uses: crowdin/github-action@v2.7.1
      with:
        download_language: ja
        config: crowdin.yml
        upload_sources: false
        download_translations: true
        push_translations: false
        export_only_approved: false
        crowdin_branch_name: ${{ inputs.crowdin-branch }}
    - name: Download zh-CN
      if: ${{ steps.cache-crowdin.outputs.cache-hit != 'true' }}
      uses: crowdin/github-action@v2.7.1
      with:
        download_language: zh-CN
        config: crowdin.yml
        upload_sources: false
        download_translations: true
        push_translations: false
        export_only_approved: false
        crowdin_branch_name: ${{ inputs.crowdin-branch }}
