# These are supported funding model platforms

github: [johnleider, KaelWD, MajesticPotatoe, yuwu9145]
patreon: vuetify
open_collective: vuetify
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/vuetify
custom: # Replace with a single custom sponsorship URL
