packages:
  - packages/*

autoInstallPeers: false

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - '@percy/core'
  - edgedriver
  - geckodriver
  - vue-demi

linkWorkspacePackages: deep

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - '@vuetify/one'
  - '@vuetify/testing-library-dom'

nodeLinker: hoisted

onlyBuiltDependencies:
  - esbuild@0.25.9

overrides:
  '@testing-library/dom': npm:@vuetify/testing-library-dom@1.0.3
  '@types/node': $@types/node
  '@vue/babel-plugin-jsx': npm:@vuetify/babel-plugin-jsx@1.6.0
  brilliant-errors>bumpp: '-'
  brilliant-errors>vitest: '-'
  vite-ssr>react-router-dom: '-'
  vite-ssr>react-ssr-prepass: '-'

patchedDependencies:
  '@mdi/js@7.4.47': patches/@mdi__js@7.4.47.patch
  '@testing-library/vue': patches/@testing-library__vue.patch

peerDependencyRules:
  allowedVersions:
    '@sentry/vue>pinia': '*'
    '@testing-library/user-event>@testing-library/dom': '*'
    '@vitejs/plugin-vue': '*'
    '@vueuse/head': '*'
    rollup: '*'
    vite: '*'

shellEmulator: true

updateConfig:
  ignoreDependencies:
    - babel-plugin-add-import-extension
