autoInstallPeers: false
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: deep
shellEmulator: true
packages:
  - 'packages/*'
updateConfig:
  ignoreDependencies:
    # 1.6.0 replaces existing extensions
    - babel-plugin-add-import-extension
overrides:
  # unused react
  vite-ssr>react-router-dom: '-'
  vite-ssr>react-ssr-prepass: '-'
  # should be devDeps
  brilliant-errors>bumpp: '-'
  brilliant-errors>vitest: '-'
  # type conflicts
  '@types/node': '$@types/node'
  # custom fork
  '@testing-library/dom': 'npm:@vuetify/testing-library-dom@1.0.2'
  '@vue/babel-plugin-jsx': 'npm:@vuetify/babel-plugin-jsx@1.6.0'
peerDependencyRules:
  allowedVersions:
    # several dependencies still say vite 4/rollup 2 but work fine anyway
    vite: '*'
    rollup: '*'
    '@vueuse/head': '*'
    '@vitejs/plugin-vue': '*'
    '@sentry/vue>pinia': '*'
    # aliased packages don't count for peerDeps apparently
    '@testing-library/user-event>@testing-library/dom': '*'
patchedDependencies:
  # fixed esm exports
  '@mdi/js@7.4.47': 'patches/@mdi__js@7.4.47.patch'
  # exposed wrapper and vm
  '@testing-library/vue': 'patches/@testing-library__vue.patch'
onlyBuiltDependencies:
  - '@percy/core'
  - 'edgedriver'
  - 'esbuild'
  - 'geckodriver'
  - 'nx'
