packages:
  - 'packages/*'

catalog:
  # Vue ecosystem
  'vue': ^3.5.13
  'vue-router': ^4.5.0
  'vue-i18n': ^11.1.1
  'vue-tsc': ^2.0.29
  '@vue/compiler-dom': ^3.5.13
  '@vue/compiler-sfc': ^3.5.13
  '@vue/reactivity': ^3.5.13
  '@vue/runtime-core': ^3.5.13
  '@vue/runtime-dom': ^3.5.13
  '@vue/shared': ^3.5.13
  '@vue/test-utils': ^2.4.6
  '@vue/babel-plugin-jsx': ^1.4.0

  # Build tools
  'vite': ^6.1.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.2
  '@vitejs/plugin-basic-ssl': ^2.0.0
  'vitest': ^3.1.1
  '@vitest/browser': ^3.1.1
  '@vitest/coverage-istanbul': ^3.1.1
  '@vitest/ui': ^3.1.1
  'vite-plugin-vuetify': ^2.1.1
  'vite-plugin-md': ^0.22.5
  'vite-plugin-pages': ^0.33.0
  'vite-plugin-pwa': ^1.0.0
  'vite-plugin-vue-layouts': ^0.11.0
  'vite-plugin-inspect': 11.0.0
  'vite-plugin-warmup': ^0.1.0
  'vite-ssr': ^0.17.2
  'unplugin-auto-import': 19.1.0
  'unplugin-vue-components': ^0.27.4
  'unplugin-fonts': 1.3.1
  '@rollup/plugin-alias': ^5.1.1
  '@rollup/plugin-babel': ^6.0.4
  '@rollup/plugin-node-resolve': ^16.0.1
  '@rollup/plugin-typescript': ^12.1.2
  'rollup': ^4.40.0
  'rollup-plugin-dts': ^6.2.1
  'rollup-plugin-sass': ^1.15.2
  'rollup-plugin-sourcemaps': ^0.6.3
  'rollup-plugin-terser': ^7.0.2

  # Babel ecosystem
  '@babel/cli': ^7.27.0
  '@babel/core': ^7.26.10
  '@babel/preset-env': ^7.26.9
  '@babel/preset-typescript': ^7.27.0
  '@babel/generator': ^7.27.0
  '@babel/types': ^7.27.0
  'babel-eslint': ^10.1.0
  'babel-plugin-add-import-extension': 1.5.1
  'babel-plugin-module-resolver': ^5.0.2
  'babel-plugin-transform-define': ^2.1.4
  'babel-polyfill': ^6.26.0

  # TypeScript tools
  'typescript': ~5.5.4
  'ts-node': ^10.9.2
  'ts-patch': ^3.3.0
  'typescript-transform-paths': ^3.5.5
  'ts-morph': ^25.0.1
  'tsx': ^4.19.3
  '@types/node': ^22.5.4
  '@types/lodash-es': ^4.17.12
  '@types/resize-observer-browser': ^0.1.11
  '@types/stringify-object': ^4.0.5
  '@types/prismjs': ^1.26.5
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-container': ^2.0.10
  '@types/babel__generator': ^7.27.0
  '@types/yargs': ^17.0.33
  '@typescript-eslint/eslint-plugin': ^7.18.0
  '@typescript-eslint/parser': ^7.18.0

  # CSS/Styling
  'sass': ^1.86.3
  'sass-embedded': ^1.86.3
  'postcss': ^8.5.3
  'autoprefixer': ^10.4.21
  'cssnano': ^7.0.6
  'csstype': ^3.1.3

  # UI and icons
  '@mdi/font': 7.4.47
  '@mdi/js': 7.4.47
  '@mdi/svg': 7.4.47
  'roboto-fontface': ^0.10.0
  '@fortawesome/fontawesome-svg-core': ^6.7.2
  '@fortawesome/free-solid-svg-icons': ^6.7.2
  '@fortawesome/vue-fontawesome': ^3.0.8

  # Utils and helpers
  'lodash-es': ^4.17.21
  'upath': ^2.0.1
  'semver': ^7.7.1
  'rimraf': ^6.0.1
  'mkdirp': ^3.0.1
  'shelljs': ^0.9.2
  'moment': ^2.30.1
  'date-fns': ^3.6.0
  'dayjs': ^1.11.13
  'luxon': ^3.6.1
  'dotenv': ^16.5.0
  'cross-spawn': ^7.0.6
  'stringify-object': ^5.0.0
  'fast-glob': ^3.3.3
  'micromatch': ^4.0.8
  'acorn-walk': ^8.3.4
  'prettier': ^3.5.3
  'deepmerge': ^4.3.1
  'glob': ^11.0.1
  'magic-string': ^0.30.17
  '@formatjs/intl': ^2.10.15

  # ESLint ecosystem
  'eslint': ^8.57.0
  'eslint-config-standard': ^17.1.0
  'eslint-formatter-codeframe': ^7.32.1
  'eslint-plugin-import': ^2.31.0
  'eslint-plugin-local-rules': ^2.0.1
  'eslint-plugin-n': ^16.6.2
  'eslint-plugin-promise': ^6.6.0
  'eslint-plugin-react': ^7.37.5
  'eslint-plugin-sonarjs': ^0.25.1
  'eslint-plugin-vue': ^9.33.0
  'eslint-plugin-vuetify': ^2.5.2
  'eslint-plugin-vitest': 0.5.4

  # Testing
  'jest': ^29.7.0
  'jest-runner-eslint': ^2.2.1
  'jest-silent-reporter': ^0.6.0
  'jsdom': ^26.1.0
  'expect': ^29.7.0
  'identity-obj-proxy': ^3.0.0
  '@testing-library/user-event': ^14.6.1
  '@testing-library/vue': ^8.1.0
  'timezone-mock': ^1.3.6

  # Documentation
  'markdownlint-cli': ^0.44.0
  'markdown-it': ^14.1.0
  'markdown-it-anchor': ^9.2.0
  'markdown-it-attrs': ^4.3.1
  'markdown-it-container': ^4.0.0
  'markdown-it-emoji': ^2.0.2
  'markdown-it-header-sections': ^1.0.0
  'markdown-it-link-attributes': ^4.0.1
  'markdown-it-prism': ^3.0.0
  'prismjs': ^1.30.0
  'prism-theme-vars': ^0.2.5
  'front-matter': ^4.0.2

  # Other dependencies
  'lerna': ^8.2.2
  'concurrently': ^9.1.2
  'piscina': ^4.9.2
  'conventional-changelog-cli': ^5.0.0
  'conventional-changelog-vuetify': ^1.2.2
  'conventional-github-releaser': ^3.1.5
  'husky': ^9.1.7
  'inquirer': ^12.5.2
  'pinia': ^3.0.2
  'vee-validate': ^4.15.0
  'yargs': ^17.7.2
  '@vuetify/one': ^2.0.0
  '@unhead/vue': ^2.0.5
  '@vueuse/head': ^1.3.1
  '@octokit/core': ^6.1.5
  '@cosmicjs/sdk': ^1.5.2
  '@sentry/vue': ^9.12.0
  '@vuelidate/core': ^2.0.3
  '@vuelidate/validators': ^2.0.4
  '@intlify/unplugin-vue-i18n': ^6.0.5
  '@intlify/devtools-types': ^11.1.3
  'swetrix': ^3.6.1
  'vue-gtag-next': ^1.14.0
  'vue-instantsearch': ^4.20.6
  'algoliasearch': ^4.24.0
  'algoliasearch-helper': ^3.24.3
  'webdriverio': ^9.12.5
  '@yankeeinlondon/builder-api': ^1.4.1
  'ajv': ^8.17.1
  'async-es': ^3.2.6
  '@emailjs/browser': ^4.4.1
  'fflate': ^0.8.2
  'isomorphic-fetch': ^3.0.0
  '@vue/language-server': ^2.2.8
  '@percy/cli': ^1.30.10
  '@percy/sdk-utils': ^1.30.10
  '@date-io/core': 3.2.0
  '@date-io/date-fns': 3.2.1
  '@date-io/dayjs': ^3.2.0
  '@date-io/luxon': ^3.2.0
  '@date-io/moment': ^3.2.0
  'cy-mobile-commands': ^0.3.0
  '@octokit/openapi-types': ^25.0.0
  '@testing-library/dom': npm:@vuetify/testing-library-dom@1.0.2
