import './addon-show-vue-markup/register'
import '@storybook/addon-knobs/register'
import '@storybook/addon-actions/register'
import '@storybook/addon-notes/register'
import '@storybook/addon-a11y/register'
import '@storybook/addon-viewport/register'
