/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('@/components/VApp/index')['VApp']
    VAutocomplete: typeof import('@/components/VAutocomplete/index')['VAutocomplete']
    VBtn: typeof import('@/components/VBtn/index')['VBtn']
    VCard: typeof import('@/components/VCard/index')['VCard']
    VCheckbox: typeof import('@/components/VCheckbox/index')['VCheckbox']
    VCol: typeof import('@/components/VGrid/index')['VCol']
    VCombobox: typeof import('@/components/VCombobox/index')['VCombobox']
    VContainer: typeof import('@/components/VGrid/index')['VContainer']
    VFileInput: typeof import('@/components/VFileInput/index')['VFileInput']
    VInput: typeof import('@/components/VInput/index')['VInput']
    VList: typeof import('@/components/VList/index')['VList']
    VListItem: typeof import('@/components/VList/index')['VListItem']
    VMain: typeof import('@/components/VMain/index')['VMain']
    VRow: typeof import('@/components/VGrid/index')['VRow']
    VSelect: typeof import('@/components/VSelect/index')['VSelect']
    VSlider: typeof import('@/components/VSlider/index')['VSlider']
    VTextarea: typeof import('@/components/VTextarea/index')['VTextarea']
    VTextField: typeof import('@/components/VTextField/index')['VTextField']
  }
}
