// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('@/components/VApp/index')['VApp']
    VAutocomplete: typeof import('@/components/VAutocomplete/index')['VAutocomplete']
    VBtn: typeof import('@/components/VBtn/index')['VBtn']
    VMain: typeof import('@/components/VMain/index')['VMain']
  }
}

export {}
