// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('@/components/VApp')['VApp']
    VAutocomplete: typeof import('@/components/VAutocomplete')['VAutocomplete']
    VBtn: typeof import('@/components/VBtn')['VBtn']
    VMain: typeof import('@/components/VMain')['VMain']
  }
}

export {}
