import {
  mdiAccount,
  mdiAtomVariant,
  mdiBeaker,
  mdiBookOpenPageVariant,
  mdiBriefcaseSearch,
  mdiCheckBold,
  mdiCodepen,
  mdiCodeTags,
  mdiCogs,
  mdiContentCopy,
  mdiDiscord,
  mdiFunction,
  mdiGithub,
  mdiInvertColors,
  mdiLinkVariant,
  mdiOpenInNew,
  mdiPageNext,
  mdiPalette,
  mdiPlayCircle,
  mdiPlusCircle,
  mdiPound,
  mdiSpeedometer,
  mdiTranslate,
  mdiViewDashboard,
  mdiVuetify,
} from '@mdi/js'

export const icons = {
  iconfont: 'mdiSvg',
  values: {
    mdiAccount,
    mdiAtomVariant,
    mdiBeaker,
    mdiBookOpenPageVariant,
    mdiBriefcaseSearch,
    mdiCheckBold,
    mdiCodepen,
    mdiCodeTags,
    mdiCogs,
    mdiContentCopy,
    mdiDiscord,
    mdiFunction,
    mdiGithub,
    mdiInvertColors,
    mdiLinkVariant,
    mdiOpenInNew,
    mdiPageNext,
    mdiPalette,
    mdiPlayCircle,
    mdiPlusCircle,
    mdiPound,
    mdiSpeedometer,
    mdiTranslate,
    mdiViewDashboard,
    mdiVuetify,
  },
}
