import {
  mdiAccount,
  mdiBeaker,
  mdiBookOpenPageVariant,
  mdiCheckBold,
  mdiCodepen,
  mdiCodeTags,
  mdiCogs,
  mdiContentCopy,
  mdiGithub,
  mdiInvertColors,
  mdiLinkVariant,
  mdiOpenInNew,
  mdiPlayCircle,
  mdiSpeedometer,
  mdiTranslate,
  mdiViewDashboard,
  mdiVuetify,
} from '@mdi/js'

export const icons = {
  iconfont: 'mdiSvg',
  values: {
    mdiAccount,
    mdiBeaker,
    mdiBookOpenPageVariant,
    mdiCheckBold,
    mdiCodepen,
    mdiCodeTags,
    mdiCogs,
    mdiContentCopy,
    mdiGithub,
    mdiInvertColors,
    mdiLinkVariant,
    mdiOpenInNew,
    mdiPlayCircle,
    mdiSpeedometer,
    mdiTranslate,
    mdiViewDashboard,
    mdiVuetify,
  },
}
