// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppBtn: typeof import('./src/components-v3/app/btn.vue')['default']
    DefaultAppBarItems: typeof import('./src/components-v3/default/app-bar-items.vue')['default']
    DefaultSearch: typeof import('./src/components-v3/default/search.vue')['default']
    DefaultSettings: typeof import('./src/components-v3/default/settings.vue')['default']
    DefaultSnackbar: typeof import('./src/components-v3/default/snackbar.vue')['default']
    DocsLinksJobs: typeof import('./src/components-v3/docs/links/jobs.vue')['default']
    DocsLinksStore: typeof import('./src/components-v3/docs/links/store.vue')['default']
    DocsLinksTeam: typeof import('./src/components-v3/docs/links/team.vue')['default']
    DocsVerticalDivider: typeof import('./src/components-v3/docs/vertical-divider.vue')['default']
    HomeActionBtns: typeof import('./src/components-v3/home/action-btns.vue')['default']
    HomeAppBar: typeof import('./src/components-v3/home/app-bar.vue')['default']
    HomeAppBarLogo: typeof import('./src/components-v3/home/app-bar-logo.vue')['default']
    HomeFooter: typeof import('./src/components-v3/home/footer.vue')['default']
    HomeSponsors: typeof import('./src/components-v3/home/sponsors.vue')['default']
    HomeView: typeof import('./src/components-v3/home/view.vue')['default']
    HomeVuetifyLogo: typeof import('./src/components-v3/home/vuetify-logo.vue')['default']
    MenusLanguage: typeof import('./src/components-v3/menus/language.vue')['default']
    MenusLearn: typeof import('./src/components-v3/menus/learn.vue')['default']
    MenusNotifications: typeof import('./src/components-v3/menus/notifications.vue')['default']
    MenusSupport: typeof import('./src/components-v3/menus/support.vue')['default']
    TogglesSettings: typeof import('./src/components-v3/toggles/settings.vue')['default']
  }
}

export { }
