// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ApiSection: typeof import('./src/components-v3/api/Section.vue')['default']
    ApiTable: typeof import('./src/components-v3/api/Table.vue')['default']
    AppBar: typeof import('./src/components-v3/app/bar/index.vue')['default']
    AppBarLanguageMenu: typeof import('./src/components-v3/app/bar/LanguageMenu.vue')['default']
    AppBarLearnMenu: typeof import('./src/components-v3/app/bar/LearnMenu.vue')['default']
    AppBarSupportMenu: typeof import('./src/components-v3/app/bar/SupportMenu.vue')['default']
    AppBarTeamLink: typeof import('./src/components-v3/app/bar/TeamLink.vue')['default']
    AppBtn: typeof import('./src/components-v3/app/btn.vue')['default']
    AppDrawer: typeof import('./src/components-v3/app-drawer/index.vue')['default']
    AppHeading: typeof import('./src/components-v3/app/Heading.vue')['default']
    AppLink: typeof import('./src/components-v3/app/Link.vue')['default']
    AppMarkdown: typeof import('./src/components-v3/app/Markdown.vue')['default']
    AppMarkup: typeof import('./src/components-v3/app/Markup.vue')['default']
    AppMenu: typeof import('./src/components-v3/app/menu/index.vue')['default']
    AppMenuList: typeof import('./src/components-v3/app/menu/List.vue')['default']
    AppMenuListGroup: typeof import('./src/components-v3/app/menu/ListGroup.vue')['default']
    AppMenuListItem: typeof import('./src/components-v3/app/menu/ListItem.vue')['default']
    AppSheet: typeof import('./src/components-v3/app/Sheet.vue')['default']
    AppToc: typeof import('./src/components-v3/app/Toc.vue')['default']
    DefaultAppBarItems: typeof import('./src/components-v3/default/app-bar-items.vue')['default']
    DefaultSearch: typeof import('./src/components-v3/default/search.vue')['default']
    DefaultSettings: typeof import('./src/components-v3/default/settings.vue')['default']
    DefaultSnackbar: typeof import('./src/components-v3/default/snackbar.vue')['default']
    DocsLinksJobs: typeof import('./src/components-v3/docs/links/jobs.vue')['default']
    DocsLinksStore: typeof import('./src/components-v3/docs/links/store.vue')['default']
    DocsLinksTeam: typeof import('./src/components-v3/docs/links/team.vue')['default']
    DocsVerticalDivider: typeof import('./src/components-v3/docs/vertical-divider.vue')['default']
    Example: typeof import('./src/components-v3/example/index.vue')['default']
    HomeActionBtns: typeof import('./src/components-v3/home/action-btns.vue')['default']
    HomeAppBar: typeof import('./src/components-v3/home/app-bar.vue')['default']
    HomeAppBarLogo: typeof import('./src/components-v3/home/app-bar-logo.vue')['default']
    HomeFooter: typeof import('./src/components-v3/home/footer.vue')['default']
    HomeSponsors: typeof import('./src/components-v3/home/sponsors.vue')['default']
    HomeView: typeof import('./src/components-v3/home/view.vue')['default']
    HomeVuetifyLogo: typeof import('./src/components-v3/home/vuetify-logo.vue')['default']
    IconsChevronDown: typeof import('./src/components-v3/icons/ChevronDown.vue')['default']
    MenusLanguage: typeof import('./src/components-v3/menus/language.vue')['default']
    MenusLearn: typeof import('./src/components-v3/menus/learn.vue')['default']
    MenusNotifications: typeof import('./src/components-v3/menus/notifications.vue')['default']
    MenusSupport: typeof import('./src/components-v3/menus/support.vue')['default']
    TogglesSettings: typeof import('./src/components-v3/toggles/settings.vue')['default']
  }
}

export { }
