<template>
  <div>
    <v-progress-linear
      bg-color="pink-lighten-3"
      color="pink-lighten-1"
      model-value="15"
    ></v-progress-linear>
    <br>
    <v-progress-linear
      bg-color="blue-grey"
      color="lime"
      model-value="30"
    ></v-progress-linear>
    <br>
    <v-progress-linear
      bg-color="success"
      color="error"
      model-value="45"
    ></v-progress-linear>
  </div>
</template>
