<template>
  <div>
    <v-progress-linear
      model-value="15"
      bg-color="pink-lighten-3"
      color="pink-lighten-1"
    ></v-progress-linear>
    <br>
    <v-progress-linear
      model-value="30"
      bg-color="blue-grey"
      color="lime"
    ></v-progress-linear>
    <br>
    <v-progress-linear
      model-value="45"
      bg-color="success"
      color="error"
    ></v-progress-linear>
  </div>
</template>
