<template>
  <div>
    <v-progress-linear
      model-value="100"
      color="red-darken-2"
      rounded
    ></v-progress-linear>
    <br>
    <v-progress-linear
      model-value="100"
      color="indigo"
      rounded
    ></v-progress-linear>
    <br>
    <v-progress-linear
      model-value="100"
      color="teal"
      rounded
    ></v-progress-linear>
    <br>
    <v-progress-linear
      model-value="100"
      color="cyan-darken-2"
      rounded
    ></v-progress-linear>
  </div>
</template>
