<template>
  <v-container
    fluid
    grid-list-lg
  >
    <v-layout
      row
      wrap
    >
      <v-flex xs12>
        <v-slider
          disabled
          label="Disabled"
          value="30"
        ></v-slider>
      </v-flex>
    </v-layout>
  </v-container>
</template>
