<template>
  <v-form>
    <v-container>
      <v-row>
        <v-col
          cols="12"
          sm="6"
          md="4"
        >
          <v-text-field
            density="default"
            label="Default"
            placeholder="Default"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="4"
        >
          <v-text-field
            density="comfortable"
            label="Comfortable"
            placeholder="Comfortable"
            variant="filled"
            rounded
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="4"
        >
          <v-text-field
            density="compact"
            label="Compact"
            placeholder="Compact"
            variant="solo"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="4"
        >
          <v-text-field
            density="default"
            label="Default"
            placeholder="Default"
            variant="underlined"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="4"
        >
          <v-text-field
            density="comfortable"
            label="Comfortable"
            placeholder="Comfortable"
            variant="plain"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          sm="6"
          md="4"
        >
          <v-text-field
            density="compact"
            label="Compact"
            placeholder="Compact"
            variant="outlined"
          ></v-text-field>
        </v-col>
      </v-row>
    </v-container>
  </v-form>
</template>
