<template>
  <v-form>
    <v-container>
      <v-row>
        <v-col
          cols="12"
          md="4"
          sm="6"
        >
          <v-text-field
            label="Regular"
            placeholder="Placeholder"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          md="4"
          sm="6"
        >
          <v-text-field
            label="Solo"
            placeholder="Placeholder"
            variant="solo"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          md="4"
          sm="6"
        >
          <v-text-field
            label="Filled"
            placeholder="Placeholder"
            variant="filled"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          md="4"
          sm="6"
        >
          <v-text-field
            label="Outlined"
            placeholder="Placeholder"
            variant="outlined"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          md="4"
          sm="6"
        >
          <v-text-field
            label="Plain"
            placeholder="Placeholder"
            variant="plain"
          ></v-text-field>
        </v-col>

        <v-col
          cols="12"
          md="4"
          sm="6"
        >
          <v-text-field
            label="Underlined"
            placeholder="Placeholder"
            variant="underlined"
          ></v-text-field>
        </v-col>
      </v-row>
    </v-container>
  </v-form>
</template>
