module.exports = {
  mixins: [
    'measurable',
    'themeable',
    'v-responsive',
  ],
  props: [
    {
      name: 'alt',
      type: 'string',
      default: 'undefined',
      source: 'v-img',
      description: {
        en: 'Alternate text for screen readers. Leave empty for decorative images',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'aspect-ratio',
      type: [
        'string',
        'number',
      ],
      default: 'undefined',
      source: 'v-responsive',
      description: {
        en: 'Calculated as `width/height`, so for a 1920x1080px image this will be `1.7778`. Will be calculated automatically if omitted',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'contain',
      type: 'boolean',
      default: 'false',
      source: 'v-img',
      description: {
        en: "Prevents the image from being cropped if it doesn't fit",
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'content-class',
      type: 'string',
      default: 'undefined',
      source: 'v-responsive',
      description: {
        en: 'Apply a custom class to the responsive content div.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'dark',
      type: 'boolean',
      default: 'false',
      source: 'themeable',
      description: {
        en: 'Applies the dark theme variant to the component. You can find more information on the Material Design documentation for [dark themes](https://material.io/design/color/dark-theme.html).',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'eager',
      type: 'boolean',
      default: 'false',
      source: 'v-img',
      description: {
        en: 'Will force the components content to render on mounted. This is useful if you have content that will not be rendered in the DOM that you want crawled for SEO.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'gradient',
      type: 'string',
      default: 'undefined',
      source: 'v-img',
      description: {
        en: 'Overlays a gradient onto the image. Only supports [linear-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) syntax, anything else should be done with classes (see examples)',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'height',
      type: [
        'number',
        'string',
      ],
      default: 'undefined',
      source: 'measurable',
      description: {
        en: 'Sets the height for the component.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'lazy-src',
      type: 'string',
      default: 'undefined',
      source: 'v-img',
      description: {
        en: 'Something to show while waiting for the main image to load, typically a small base64-encoded thumbnail. Has a slight blur filter applied.\n\nUse [vuetify-loader](https://github.com/vuetifyjs/vuetify-loader) to generate automatically',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'light',
      type: 'boolean',
      default: 'false',
      source: 'themeable',
      description: {
        en: 'Applies the light theme variant to the component.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'max-height',
      type: [
        'number',
        'string',
      ],
      default: 'undefined',
      source: 'measurable',
      description: {
        en: 'Sets the maximum height for the component.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'max-width',
      type: [
        'number',
        'string',
      ],
      default: 'undefined',
      source: 'measurable',
      description: {
        en: 'Sets the maximum width for the component.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'min-height',
      type: [
        'number',
        'string',
      ],
      default: 'undefined',
      source: 'measurable',
      description: {
        en: 'Sets the minimum height for the component.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'min-width',
      type: [
        'number',
        'string',
      ],
      default: 'undefined',
      source: 'measurable',
      description: {
        en: 'Sets the minimum width for the component.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'options',
      type: 'object',
      default: {},
      source: 'v-img',
      description: {
        en: 'Options that are passed to the [Intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) constructor.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'position',
      type: 'string',
      default: "'center center'",
      source: 'v-img',
      description: {
        en: 'Overrides the default to change which parts get cropped off. Uses the same syntax as [`background-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-position)',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'sizes',
      type: 'string',
      default: 'undefined',
      source: 'v-img',
      description: {
        en: 'For use with `srcset`, see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes)',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'src',
      type: [
        'string',
        'object',
      ],
      default: 'undefined',
      source: 'v-img',
      description: {
        en: 'The image URL. This prop is mandatory',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'srcset',
      type: 'string',
      default: 'undefined',
      source: 'v-img',
      description: {
        en: 'A set of alternate images to use based on device size. [Read more...](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset)',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'transition',
      type: [
        'boolean',
        'string',
      ],
      default: 'fade-transition',
      source: 'v-img',
      description: {
        en: 'The transition to use when switching from `lazy-src` to `src`',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'width',
      type: [
        'number',
        'string',
      ],
      default: 'undefined',
      source: 'measurable',
      description: {
        en: 'Sets the width for the component.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
  ],
  slots: [
    {
      name: 'default',
      description: {
        en: 'The default Vue slot.',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'placeholder',
      description: {
        en: 'Slot for image placeholder',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
  ],
  events: [
    {
      name: 'error',
      value: 'object | string',
      description: {
        en: 'Emitted when there is an error',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
    {
      name: 'load',
      value: 'object | string',
      description: {
        en: 'Emitted when image is loaded',
        ja: '',
        'zh-Hans': '',
        'eo-UY': '',
      },
    },
  ],
  functions: [],
}
