import '@percy/cypress'
import 'cypress-file-upload'
import 'cy-mobile-commands'
import 'cypress-real-events/support'
import '@mdi/font/css/materialdesignicons.css'
import './mount'
import './selector'
