<template>
  <section>
    <v-layout>
      <v-flex
        text-xs-center
        xs12
      >
        <v-btn
          class="mt-5"
          href="/examples/layouts/sandbox"
          target="_blank"
          color="primary"
          large="large"
          dark="dark"
        >Go to Sandbox</v-btn>
      </v-flex>
    </v-layout>
  </section>
</template>
