module.exports = {
  components: [
    'VCalendarCategory',
    'VColorPickerCanvas',
    'VColorPickerSwatches',
    'VCounter',
    'VData',
    'VDatePickerDateTable',
    'VDatePickerHeader',
    'VDatePickerMonthTable',
    'VDatePickerTitle',
    'VDatePickerYears',
    'VLabel',
    'VMessages',
    'VPicker',
    'VTableOverflow',
    'VTimePickerClock',
    'VTimePickerTitle',
    'VVirtualTable',
    'VTreeviewNode',
  ],
  props: {
    'v-app': [
      'dark',
      'light',
    ],
    'v-autocomplete': [
      'activator',
      'closeOnClick',
      'closeOnContentClick',
      'nudgeBottom',
      'nudgeLeft',
      'nudgeRight',
      'nudgeTop',
      'nudgeWidth',
      'offsetX',
      'offsetY',
      'transition',
    ],
    'v-bottom-sheet': [
      'close-delay',
      'open-delay',
      'return-value',
    ],
    'v-combobox': [
      'activator',
      'closeOnClick',
      'closeOnContentClick',
      'nudgeBottom',
      'nudgeLeft',
      'nudgeRight',
      'nudgeTop',
      'nudgeWidth',
      'offsetX',
      'offsetY',
      'transition',
    ],
    'v-dialog': [
      'close-delay',
      'open-delay',
      'return-value',
    ],
    'v-overflow-btn': [
      'activator',
      'closeOnClick',
      'closeOnContentClick',
      'delimiters',
      'nudgeBottom',
      'nudgeLeft',
      'nudgeRight',
      'nudgeTop',
      'nudgeWidth',
      'offsetX',
      'offsetY',
      'transition',
    ],
    'v-checkbox': [
      'height',
      'loading',
    ],
    'v-radio': [
      'height',
    ],
    'v-radio-group': [
      'color',
      'height',
      'loading',
    ],
    'v-switch': [
      'height',
    ],
    'v-window': [
      'mandatory',
      'max',
      'multiple',
    ],
    'v-file-input': [
      'readonly',
    ],
    'v-tooltip': [
      'dark',
      'light',
    ],
  },
}
