import './styles/main.sass'
export * from './components'
// export * from './directives'
// export { default as colors } from './util/colors'
export { VuetifyInstall as default } from './install'
// export { useVuetify } from './framework'
