name: Close issues
on:
  push:
    branches:
    - dev
    - next
    - v3-stable
    - v2-stable
    - v2-dev

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  close:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'vuetifyjs'
    steps:
      - uses: vuetifyjs/close-action@c0a4a544489ed6add12c6b899d18c8042db411a5 # master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
