<template>
  <div>
    <v-progress-linear
      color="light-blue"
      height="10"
      value="10"
      striped
    ></v-progress-linear>
    <br>
    <v-progress-linear
      color="light-green darken-4"
      height="10"
      value="20"
      striped
    ></v-progress-linear>
    <br>
    <v-progress-linear
      height="10"
      value="45"
      striped
      color="lime"
    ></v-progress-linear>
    <br>
    <v-progress-linear
      value="60"
      height="10"
      striped
      color="deep-orange"
    ></v-progress-linear>
  </div>
</template>
